apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- secret.yaml
- pvc.yaml
- ingress.yaml
- hpa.yaml

namespace: spark-hub

commonLabels:
  app.kubernetes.io/name: spark-hub-backend
  app.kubernetes.io/instance: prod
  app.kubernetes.io/part-of: spark-hub
  app.kubernetes.io/managed-by: kustomize 