apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-hub-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # 根据实际需求调整
  storageClassName: standard  # 根据集群提供的存储类调整 