apiVersion: v1
kind: Secret
metadata:
  name: spark-hub-db-credentials
type: Opaque
data:
  # 注意：实际部署时应该使用正确的base64编码值
  # 使用命令生成: echo -n "your-username" | base64
  username: Yml0bWFw  # base64编码的"bitmap"
  # 使用命令生成: echo -n "your-password" | base64
  password: Yml0bWFwQDY2Ng==  # base64编码的"bitmap@666" 